# Generated by Django 6.0.5 on 2026-06-18 16:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('department', models.CharField(max_length=100)),
                ('current_semester', models.IntegerField(default=1)),
                ('year_of_study', models.CharField(choices=[('Year 1', 'Year 1'), ('Year 2', 'Year 2'), ('Year 3', 'Year 3'), ('Year 4', 'Year 4')], max_length=20)),
                ('current_gpa', models.FloatField(default=0.0)),
                ('semester_gpa', models.FloatField(default=0.0)),
                ('cgpa', models.FloatField(default=0.0)),
                ('attendance_percentage', models.FloatField(default=0.0)),
                ('course_failures', models.IntegerField(default=0)),
                ('study_hours_per_day', models.FloatField(default=0.0)),
                ('library_visits_per_week', models.IntegerField(default=0)),
                ('assignment_submission_rate', models.FloatField(default=100.0)),
                ('participation_score', models.FloatField(default=5.0)),
                ('family_income', models.FloatField(blank=True, null=True)),
                ('scholarship', models.BooleanField(default=False)),
                ('part_time_job', models.BooleanField(default=False)),
                ('tuition_payment_delay_days', models.IntegerField(default=0)),
                ('parental_education', models.CharField(blank=True, max_length=50)),
                ('internet_access', models.BooleanField(default=True)),
                ('travel_time_minutes', models.IntegerField(default=0)),
                ('stress_index', models.FloatField(default=5.0)),
                ('last_prediction_probability', models.FloatField(blank=True, null=True)),
                ('last_prediction_date', models.DateTimeField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students_student',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DropoutPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropout_probability', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('prediction_result', models.BooleanField()),
                ('threshold_used', models.FloatField(default=0.4)),
                ('confidence_score', models.FloatField()),
                ('input_data', models.JSONField(default=dict)),
                ('key_factors', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='students.student')),
            ],
            options={
                'db_table': 'students_dropout_predictions',
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('subjects_taught', models.TextField(help_text='Comma-separated subjects')),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('class_assigned', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teachers_teacher_profile',
            },
        ),
    ]
