# Generated by Django 6.0.5 on 2026-06-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='joining_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subjects_taught',
            field=models.TextField(blank=True, null=True),
        ),
    ]
